# Edit your save location (x:\location\subdirectory for Windows, /home/user/location for Linix)
saveLocation: /home/rob/wordSorterTemp/

database:
  driverClass: com.mysql.jdbc.Driver
  user: username
  password: password
  url: jdbc:mysql://192.168.168.5/wordlist #Home
  
  
server:
  applicationConnectors:
    - type: http
      port: 7050
  adminConnectors:
    - type: http
      port: 7051
