# Edit your save location (x:\location\subdirectory for Windows, /home/user/location for Linix)
saveLocation: /home/javadev/pproj/WordSorter/Upload
# saveLocation: C:\Users\Rob\Desktop\Upload_Files\
# saveLocation: /home/rob/WordSorter/SaveLocation/

database:
  driverClass: com.mysql.jdbc.Driver
  user: wordlistuser
  password: 123123a
  #url: jdbc:mysql://192.168.168.5/wordlist #Home
  url: jdbc:mysql://localhost/wordlist
  
  
server:
  applicationConnectors:
    - type: http
      port: 7050
  adminConnectors:
    - type: http
      port: 7051
