message: This is a message defined in the configuration file.
messageRepetitions: 9

database:
  driverClass: com.mysql.jdbc.Driver
  user: wordlistuser
  password: 123123a
  url: jdbc:mysql://192.168.168.5/wordlist